### ISSUE TITLE
Support for slide timer data

### ISSUE THREAD

**Issue by fiendskrah** [Kainev/AutoSplit64#1]
Just a suggestion for additional functionality, I'm not sure how difficult this would be or if it's even possible but:

If AS64 works by capturing the image of the star count/xcam etc., would it be possible to capture the area where the timer for the Princess Secret Slide appears and log the time, maybe drop the values in a flat text file? 

This could be use to pool data on slide finishes from runs, but I imagine the functionality could be built out to batch single star data using the Usamune drive, because it's the same capture area, right?

**Comment by wRadion** [comment]
Hey!
I don't think this should be a part of an autosplitter. Maybe a software dedicated to stats or something?

**Comment by kainev** [comment]
Sorry, the project was inactive between 2020 - 2022.

Unfortunately the models used to classify the star count are trained to only recognize the specific star counts in Mario, it would require a disproportionate amount of effort to build a system to extract the exact slide data by classifying the timer.

The new version of Autosplit64 (found in the development branch) however makes use of a plugin architecture, so it will be possible for anyone to inject extra functionality such as stat collection. An easier way to potentially implement this would be to detect the presence of the timer appearing (not the value), and internally track the time until Mario enters an x-cam state.
